version: "3.8"

services:
  sketchup-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sketchup-glb-api
    environment:
      BASE_PUBLIC_URL: https://glbup.funtools.cloud/uploads_glb
      API_KEYS: jsb-123456,abc-987654,lmd-555000
    ports:
      - "8088:80"
    volumes:
      - sketchup_data:/var/www/html/uploads_glb

volumes:
  sketchup_data:
