version: "3.8"

services:
  sketchup-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sketchup-glb-api

    environment:
      BASE_PUBLIC_URL: ${BASE_PUBLIC_URL}
      API_KEYS: ${API_KEYS}

    ports:
      - "8088:80"

    volumes:
      - sketchup_data:/var/www/html/uploads_glb

volumes:
  sketchup_data:
